### ISSUE TITLE
Feature request: support `version: "1"`

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/julia-buildkite-plugin#3]
If I try this:
```yaml
steps:
  - label: "Julia 1"
    plugins:
      - JuliaCI/julia#v0.6:
          version: "1"
```

I get this error (see e.g. [this log](https://buildkite.com/julialang/neuralpde-dot-jl/builds/25)):
```
Downloading Julia 1
Source URL: https://julialang-s3.julialang.org/bin/linux/x64/1/julia-1-latest-linux-x86_64.tar.gz
https://julialang-s3.julialang.org/bin/linux/x64/1/julia-1-latest-linux-x86_64.tar.gz:
2021-01-08 10:27:32 ERROR 404: Not Found.
```

**Comment by DilumAluthge** [comment]
It would be great if we could support `version: "1"`.

cc: @maleadt 
cc: @ChrisRackauckas (who is trying to use this in NeuralPDE.jl)
cc: @saschamann (who might be able to help out, since this functionality already exists in the `setup-julia` GitHub Action)

**Comment by SaschaMann** [comment]
`setup-julia` uses [node-semver](https://github.com/npm/node-semver). It has a CLI but I don't know if you'd want to introduce that as dependency. If you only want to support `1` and `1.1` but not caret or tilde ranges, a simple bash script that splits the version and takes whatever is the highest that starts with `1` is probably enough.
